" {{{ GET PLUGINS
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source ~/.vimrc
endif

call plug#begin('~/.vim/plugged')
    if has('nvim')
        Plug 'neoclide/coc.nvim', {'branch': 'release'}
        " requires yarn
        Plug 'neoclide/coc-tsserver', {'do': 'yarn install --frozen-lockfile'}
        Plug 'neoclide/coc-eslint', {'do': 'yarn install --frozen-lockfile'}
        Plug 'neoclide/coc-python', {'do': 'yarn install --frozen-lockfile'}
        Plug 'neoclide/coc-json', {'do': 'yarn install --frozen-lockfile'}
    endif
    Plug 'mintelm/gruvbox', {'branch': 'colorchanges'}
    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
    Plug 'junegunn/fzf.vim'                     " fzf <3 vim
    Plug 'itchyny/lightline.vim'                " bottom info bar
    Plug 'mengelbrecht/lightline-bufferline'    " buftab line
    Plug 'airblade/vim-gitgutter'               " git info on left bar
    Plug 'tpope/vim-fugitive'                   " git branch info etc.
    Plug 'leafgarland/typescript-vim'           " syntax highlighting
    Plug 'vimwiki/vimwiki'                      " my wiki
call plug#end()
" }}}


" {{{ GENERAL
syntax enable
filetype plugin on
set title
set titlestring=vim\ %{expand(\"%:p:~\")}

" tabs
let tabsize=4
set expandtab
call utils#SetTabs(tabsize)
au FileType c,cpp,objc,objcpp,sh,make call utils#SetTabs(8)

" highlight characters over 80 line length if c
highlight ColorColumn ctermbg=magenta
au FileType c,cpp,objc,objcpp,sh,make call matchadd('ColorColumn', '\%>80v.\+', 100)
au FileType typescript call matchadd('ColorColumn', '\%>140v.\+', 100)

" colors
let g:gruvbox_contrast_dark='hard'
set background=dark
set termguicolors               " activate 256 color support
colorscheme gruvbox             " set color scheme
highlight SignColumn ctermbg=234 guibg=#1d2021
highlight CursorLineNr ctermfg=214 ctermbg=234 guifg=#fabd2f guibg=#1d2021
highlight CursorLine ctermbg=234 guibg=#1d2021

" others
set number                      " activate line numbers
set relativenumber              " relative numbers from current line
set mouse=a
set cursorline                  " highlight current line
set showmatch                   " highlight matching [{()}]
set noshowmode                  " dont show --insert-- (as lightline does)
set scrolloff=5                 " scroll before end of lines
set sidescrolloff=15            " scroll before side end of lines
set clipboard=unnamed           " sync system and vim clipboard
set ttimeoutlen=5               " time in ms to wait for a key code sequence to complete
set signcolumn=yes              " always show signcolumns
set hidden                      " allow to open new buffer if last was unsafed
set nobackup|set nowritebackup  " some server have issues with backup files
set updatetime=300              " smaller updatetime for cursorhold
set shortmess+=c                " don't give ins-completion-menu messages.
set synmaxcol=500               " don't highlight after 500 chars, reduces lag
" }}}


" {{{ MAPS AND KEYBINDS
let mapleader = ","

" unmap
map <C-b> <Nop>
map <C-f> <Nop>

" navigation
map [q :cprev<CR>
map ]q :cnext<CR>
map [Q :cfirst<CR>
map ]Q :clast<CR>
nnoremap <C-n> :bnext<CR>
nnoremap <C-p> :bprev<CR>

" turn off search highlight with <space>
nnoremap <silent><Space> :nohlsearch<Bar>:echo<CR>

" typos
command W w
command Wq wq
command Q q

" fzf
map <leader>b :Buffers<CR>
map <leader>f :Files<CR>
map <leader>gf :GFiles<CR>

" fugitive
map <leader>gs :Gstatus<CR>

" gitgutter
map <leader>hv <Plug>(GitGutterPreviewHunk)
map <leader>ha <Plug>(GitGutterStageHunk)
map <leader>hr <Plug>(GitGutterUndoHunk)
nmap ]h <Plug>(GitGutterNextHunk)
nmap [h <Plug>(GitGutterPrevHunk)

" coc
nmap <leader>qf  <Plug>(coc-fix-current)
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gr <Plug>(coc-references)
nmap <leader>rn <Plug>(coc-rename)
map <leader>cr :CocRestart<CR><CR>
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)
nmap <leader>? :call CocAction('diagnosticInfo') <CR>
xmap <leader>sf <Plug(coc-format-selected)
nmap <leader>sf <Plug(coc-format-selected)

" lightline bufferline
nmap <Leader>1 <Plug>lightline#bufferline#go(1)
nmap <Leader>2 <Plug>lightline#bufferline#go(2)
nmap <Leader>3 <Plug>lightline#bufferline#go(3)
nmap <Leader>4 <Plug>lightline#bufferline#go(4)
nmap <Leader>5 <Plug>lightline#bufferline#go(5)
nmap <Leader>6 <Plug>lightline#bufferline#go(6)
nmap <Leader>7 <Plug>lightline#bufferline#go(7)
nmap <Leader>8 <Plug>lightline#bufferline#go(8)
nmap <Leader>9 <Plug>lightline#bufferline#go(9)
nmap <Leader>0 <Plug>lightline#bufferline#go(10)
nmap <Leader>d1 <Plug>lightline#bufferline#delete(1)
nmap <Leader>d2 <Plug>lightline#bufferline#delete(2)
nmap <Leader>d3 <Plug>lightline#bufferline#delete(3)
nmap <Leader>d4 <Plug>lightline#bufferline#delete(4)
nmap <Leader>d5 <Plug>lightline#bufferline#delete(5)
nmap <Leader>d6 <Plug>lightline#bufferline#delete(6)
nmap <Leader>d7 <Plug>lightline#bufferline#delete(7)
nmap <Leader>d8 <Plug>lightline#bufferline#delete(8)
nmap <Leader>d9 <Plug>lightline#bufferline#delete(9)
nmap <Leader>d0 <Plug>lightline#bufferline#delete(10)
" }}}


" {{{ LIGHTLINE
set laststatus=2
set showtabline=2

let g:lightline = {
    \ 'colorscheme': 'gruvbox',
    \ 'active': {
    \   'left': [ [ 'mode', 'paste' ],
    \             [ 'readonly', 'filename', 'modified' ],
    \             [ 'gitbranch', 'githunks' ] ],
    \
    \   'right': [ [ 'lineinfo' ],
    \              [ 'percent' ],
    \              [ 'cocstatus', 'fileformat', 'fileencoding', 'filetype', 'cocerrors', 'cocwarns', 'cocinfos', 'cochints' ] ],
    \ },
    \ 'tabline': {
    \   'left': [ ['buffers'] ],
    \   'right': [ [ '' ] ],
    \ },
    \ 'component_function': {
    \   'cocstatus': 'utils#CocShortStatus',
    \   'githunks': 'utils#GitStatus',
    \   'gitbranch': 'FugitiveHead',
    \ },
    \ 'component_expand': {
    \   'cocerrors': 'utils#CocErrors',
    \   'cocwarns': 'utils#CocWarnings',
    \   'cocinfos': 'utils#CocInfos',
    \   'cochints': 'utils#CocHints',
    \   'buffers': 'lightline#bufferline#buffers',
    \ },
    \ 'component_type': {
    \   'cocerrors': 'cocerror',
    \   'cocwarns': 'cocwarn',
    \   'cocinfos': 'cocinfo',
    \   'cochints': 'cochint',
    \   'buffers': 'tabsel',
    \ },
\ }
autocmd User CocDiagnosticChange call lightline#update()

" make bufferline clickable
let g:lightline#bufferline#clickable = 1 
let g:lightline.component_raw = {'buffers': 1}

" always show ordinal numbers
let g:lightline#bufferline#show_number = 2
let g:lightline#bufferline#composed_number_map = {
\ 1:  '⑴ ', 2:  '⑵ ', 3:  '⑶ ', 4:  '⑷ ', 5:  '⑸ ',
\ 6:  '⑹ ', 7:  '⑺ ', 8:  '⑻ ', 9:  '⑼ ', 10: '⑽ ',
\ 11: '⑾ ', 12: '⑿ ', 13: '⒀ ', 14: '⒁ ', 15: '⒂ ',
\ 16: '⒃ ', 17: '⒄ ', 18: '⒅ ', 19: '⒆ ', 20: '⒇ '}
" }}}


" {{{ COC
if has('nvim')
    let g:coc_status_error_sign=''
    let g:coc_status_warning_sign=''
    let g:coc_status_info_sign=''
    let g:coc_status_hint_sign=''

    " highlight comments in json correctly
    autocmd FileType json syntax match Comment +\/\/.\+$+

    " highlight the symbol and its references when holding the cursor
    autocmd CursorHold * silent call CocActionAsync('highlight')

    " use <c-space>for trigger completion
    inoremap <silent><expr> <c-space> coc#refresh()

    " use <tab> and <s-tab> to navigate through completion
    inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
    inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
    let g:coc_snippet_next = '<TAB>'
    let g:coc_snippet_prev = '<S-TAB>'

    " use <cr> to confirm completion
    inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

    " Use K to show documentation in preview window
    nnoremap <silent> K :call utils#ShowDocumentation()<CR>

    " Add `:OI` command for organize imports of the current buffer.
    command! -nargs=0 OI   :call     CocAction('runCommand', 'editor.action.organizeImport')

    " Add `:Format` command to format current buffer.
    command! -nargs=0 Format :call CocAction('format')
endif
" }}}


" {{{ OTHER PLUGINS
" fzf
let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6, 'highlight': 'Debug' } }

" gitgutter
let g:gitgutter_map_keys = 0
highlight GitGutterAdd ctermfg=142 ctermbg=234 guifg=#b8bb26 guibg=#1d2021
highlight GitGutterDelete ctermfg=167 ctermbg=234 guifg=#fb4934 guibg=#1d2021
highlight GitGutterChange ctermfg=108 ctermbg=234 guifg=#8ec07c guibg=#1d2021
highlight GitGutterChangeDelete ctermfg=108 ctermbg=234 guifg=#8ec07c guibg=#1d2021

" vimwiki
let g:vimwiki_list = [{ 'path': '~/mintelm/wiki/', 'path_html': '~/mintelm/wiki/html' }]
" }}}
