" {{{ GET PLUGINS
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source ~/.vimrc
endif

call plug#begin('~/.vim/plugged')
    if has('nvim')
        Plug 'neoclide/coc.nvim', {'branch': 'release'}
    endif
    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
    Plug 'junegunn/fzf.vim'                     " fzf <3 vim
    Plug 'mintelm/gruvbox'                      " color scheme
    Plug 'itchyny/lightline.vim'                " bottom info bar
    Plug 'airblade/vim-gitgutter'               " git info on left bar
    Plug 'tpope/vim-fugitive'                   " git branch info etc.
    Plug 'scrooloose/nerdcommenter'             " ez comments
    Plug 'mcchrish/nnn.vim'                     " floating file browser
    Plug 'leafgarland/typescript-vim'           " syntax highlighting
call plug#end()
" }}}


" {{{ GENERAL
" tabs
let tabsize=4
set expandtab
call utils#SetTabs(tabsize)
au FileType c,cpp,objc,objcpp,sh,make call utils#SetTabs(8)

" highlight characters over 80 line length if c
highlight ColorColumn ctermbg=magenta
au FileType c,cpp,objc,objcpp,sh,make call matchadd('ColorColumn', '\%>80v.\+', 100)

set background=dark
colorscheme gruvbox             " set color scheme

syntax enable                   " enable syntax processing
filetype plugin on              " allow vim to recognize filetypes
set number                      " activate line numbers
set relativenumber              " relative numbers from current line
set termguicolors               " activate 256 color support
set mouse=a

set cursorline                  " highlight current line
set showmatch                   " highlight matching [{()}]
set noshowmode                  " dont show --insert-- (as lightline does)
set scrolloff=5                 " scroll before end of lines
set sidescrolloff=15            " scroll before side end of lines
set clipboard=unnamed           " sync system and vim clipboard
" }}}


" {{{ MAPS AND KEYBINDS
let mapleader = ","

command W w
command Wq wq
command Q q

" unmap
map <C-b> <Nop>
map <C-f> <Nop>

map <leader>e :NnnPicker '%:p:h'<CR>
map <leader>b :Buffers<CR>
map <leader>f :Files<CR>
map <leader>gf :GFiles<CR>
map <leader>k <Plug>NERDCommenterToggle
map <leader>gs :Gstatus<CR>
map <leader>qf :CocFix<CR>
map <leader>hv <Plug>(GitGutterPreviewHunk)
map <leader>ha <Plug>(GitGutterStageHunk)
nmap ]h <Plug>(GitGutterNextHunk)
nmap [h <Plug>(GitGutterPrevHunk)
map [q :cprev<CR>
map ]q :cnext<CR>
map [Q :cfirst<CR>
map ]Q :clast<CR>

" Remap keys for gotos
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Symbol renaming.
nmap <leader>rn <Plug>(coc-rename)

" turn off search highlight with <space>
nnoremap <silent><Space> :nohlsearch<Bar>:echo<CR> 
" }}}


" {{{ LIGHTLINE
set laststatus=2

let g:lightline = {
    \ 'colorscheme': 'gruvbox',
    \ 'active': {
    \   'left': [ [ 'mode', 'paste' ],
    \             [ 'cocstatus', 'readonly', 'filename', 'modified' ],
    \             [ 'gitbranch', 'githunks' ] ],
    \
    \   'right': [ [ 'lineinfo' ],
    \              [ 'percent' ],
    \              [ 'fileformat', 'fileencoding', 'filetype' ] ],
    \ },
    \ 'component_function': {
    \   'cocstatus': 'coc#status',
    \   'githunks': 'utils#GitStatus',
    \   'gitbranch': 'FugitiveHead',
    \ },
\ }
" }}}


" {{{ COC
set hidden                      " if hidden is not set, TextEdit might fail.
set nobackup|set nowritebackup  " Some server have issues with backup files
set updatetime=300              " Smaller updatetime for CursorHold
set shortmess+=c                " don't give ins-completion-menu messages.
set signcolumn=yes              " always show signcolumns

" highlight comments in json correctly
autocmd FileType json syntax match Comment +\/\/.\+$+

" use <c-space>for trigger completion
inoremap <silent><expr> <c-space> coc#refresh()

" use <tab> and <s-tab> to navigate through completion
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
let g:coc_snippet_next = '<TAB>'
let g:coc_snippet_prev = '<S-TAB>'

" use <cr> to confirm completion
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

" Use K to show documentation in preview window
function! s:show_documentation()
    if (index(['vim','help'], &filetype) >= 0)
        execute 'h '.expand('<cword>')
    else
        call CocAction('doHover')
    endif
endfunction
nnoremap <silent> K :call <SID>show_documentation()<CR>
" }}}


" {{{ OTHER PLUGINS
" Add spaces after comment delimiters by default
let g:NERDSpaceDelims = 1
" Use compact syntax for prettified multi-line comments
let g:NERDCompactSexyComs = 1
" Enable trimming of trailing whitespace when uncommenting
let g:NERDTrimTrailingWhitespace = 1
" Enable NERDCommenterToggle to check all selected lines is commented or not 
let g:NERDToggleCheckAllLines = 1
" nnn command
let g:nnn#command = 'nnn -Q'
" floating fuzzy finder
let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6, 'highlight': 'Debug' } }
" floating nnn
let g:nnn#layout = { 'window': { 'width': 0.9, 'height': 0.6, 'highlight': 'Debug' } }
" disable standard hotkeys
let g:gitgutter_map_keys = 0
" }}}
