" {{{ GET PLUGINS
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source ~/.vimrc
endif

call plug#begin('~/.vim/plugged')
    if has('nvim')
        Plug 'neoclide/coc.nvim', {'branch': 'release'}
    endif
    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
    Plug 'junegunn/fzf.vim'                     " fzf <3 vim
    Plug 'mintelm/gruvbox'                      " color scheme
    Plug 'itchyny/lightline.vim'                " bottom info bar
    Plug 'airblade/vim-gitgutter'               " git info on left bar
    Plug 'tpope/vim-fugitive'                   " git branch info etc.
    Plug 'leafgarland/typescript-vim'           " syntax highlighting
    Plug 'vimwiki/vimwiki'                      " my wiki
call plug#end()
" }}}


" {{{ GENERAL
set title
set titlestring=vim\ %{expand(\"%:p:~\")}

" tabs
let tabsize=4
set expandtab
call utils#SetTabs(tabsize)
au FileType c,cpp,objc,objcpp,sh,make call utils#SetTabs(8)

" highlight characters over 80 line length if c
highlight ColorColumn ctermbg=magenta
au FileType c,cpp,objc,objcpp,sh,make call matchadd('ColorColumn', '\%>80v.\+', 100)
au FileType typescript call matchadd('ColorColumn', '\%>140v.\+', 100)

" colors
let g:gruvbox_contrast_dark='hard'
set background=dark
set termguicolors               " activate 256 color support
colorscheme gruvbox             " set color scheme

" others
syntax enable                   " enable syntax processing
filetype plugin on              " allow vim to recognize filetypes
set number                      " activate line numbers
set relativenumber              " relative numbers from current line
set mouse=a
set cursorline                  " highlight current line
set showmatch                   " highlight matching [{()}]
set noshowmode                  " dont show --insert-- (as lightline does)
set scrolloff=5                 " scroll before end of lines
set sidescrolloff=15            " scroll before side end of lines
set clipboard=unnamed           " sync system and vim clipboard
set ttimeoutlen=5               " time in ms to wait for a key code sequence to complete
" }}}


" {{{ MAPS AND KEYBINDS
let mapleader = ","

" unmap
map <C-b> <Nop>
map <C-f> <Nop>

" navigation
map [q :cprev<CR>
map ]q :cnext<CR>
map [Q :cfirst<CR>
map ]Q :clast<CR>

" turn off search highlight with <space>
nnoremap <silent><Space> :nohlsearch<Bar>:echo<CR>

" typos
command W w
command Wq wq
command Q q

" fzf
map <leader>b :Buffers<CR>
map <leader>f :Files<CR>
map <leader>gf :GFiles<CR>

" fugitive
map <leader>gs :Gstatus<CR>

" gitgutter
map <leader>hv <Plug>(GitGutterPreviewHunk)
map <leader>ha <Plug>(GitGutterStageHunk)
map <leader>hr <Plug>(GitGutterUndoHunk)
nmap ]h <Plug>(GitGutterNextHunk)
nmap [h <Plug>(GitGutterPrevHunk)

" coc
nmap <leader>qf  <Plug>(coc-fix-current)
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gr <Plug>(coc-references)
nmap <leader>rn <Plug>(coc-rename)
map <leader>cr :CocRestart<CR><CR>
" }}}


" {{{ LIGHTLINE
set laststatus=2
let g:lightline = {
    \ 'colorscheme': 'gruvbox',
    \ 'active': {
    \   'left': [ [ 'mode', 'paste' ],
    \             [ 'cocstatus', 'readonly', 'filename', 'modified' ],
    \             [ 'gitbranch', 'githunks' ] ],
    \
    \   'right': [ [ 'lineinfo' ],
    \              [ 'percent' ],
    \              [ 'fileformat', 'fileencoding', 'filetype' ] ],
    \ },
    \ 'component_function': {
    \   'cocstatus': 'coc#status',
    \   'githunks': 'utils#GitStatus',
    \   'gitbranch': 'FugitiveHead',
    \ },
\ }
" }}}


" {{{ COC
set hidden                      " if hidden is not set, TextEdit might fail.
set nobackup|set nowritebackup  " Some server have issues with backup files
set updatetime=300              " Smaller updatetime for CursorHold
set shortmess+=c                " don't give ins-completion-menu messages.
set signcolumn=yes              " always show signcolumns

if has('nvim')
    " don't highlight virtual text
    highlight CocErrorVirtualText ctermfg=Red  guifg=#ff0000
    highlight CocWarningVirtualText ctermfg=Red  guifg=#ff0000

    " highlight comments in json correctly
    autocmd FileType json syntax match Comment +\/\/.\+$+

    " highlight the symbol and its references when holding the cursor
    autocmd CursorHold * silent call CocActionAsync('highlight')

    " use <c-space>for trigger completion
    inoremap <silent><expr> <c-space> coc#refresh()

    " use <tab> and <s-tab> to navigate through completion
    inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
    inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
    let g:coc_snippet_next = '<TAB>'
    let g:coc_snippet_prev = '<S-TAB>'

    " use <cr> to confirm completion
    inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

    " Use K to show documentation in preview window
    nnoremap <silent> K :call utils#ShowDocumentation()<CR>

    " Add `:OI` command for organize imports of the current buffer.
    command! -nargs=0 OI   :call     CocAction('runCommand', 'editor.action.organizeImport')

    " Add `:Format` command to format current buffer.
    command! -nargs=0 Format :call CocAction('format')
endif
" }}}


" {{{ OTHER PLUGINS
" floating fuzzy finder
let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6, 'highlight': 'Debug' } }
" disable standard hotkeys
let g:gitgutter_map_keys = 0
let g:vimwiki_list = [{ 'path': '~/.vim/wiki/', 'path_html': '~/.vim/wiki_html/' }]
" }}}
