return {
    'lukas-reineke/indent-blankline.nvim',
    opts = {
        show_current_context = false,
        show_first_indent_level = false,
        show_trailing_blankline_indent = false,
        filetype_exclude = {
            'startify',
            'dashboard',
            'log',
            'fugitive',
            'gitcommit',
            'packer',
            'vimwiki',
            'markdown',
            'json',
            'txt',
            'vista',
            'help',
            'NvimTree',
            'git',
            'TelescopePrompt',
            'undotree',
            'flutterToolsOutline',
            'org',
            'orgagenda',
            '', -- for all buffers without a file type
        },
        buftype_exclude = {
            'terminal',
            'nofile',
        },
        context_patterns = {
            'class',
            'function',
            'method',
            'block',
            'list_literal',
            'selector',
            '^if',
            '^table',
            'if_statement',
            'while',
            'for',
        },
    },
}
