# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# checks to see if we are in a windows or linux dir
function isWinDir {
    case `pwd -P` in
        /mnt/c/*) return $(true);;
        /mnt/d/*) return $(true);;
        *) return $(false);;
    esac
}
# wrap the git command to either run windows git or linux
function git {
    if (isWinDir && [[ $(grep -i microsoft /proc/version) ]]); then
        git.exe "$@"
    else
        /usr/bin/git "$@"
    fi
}

# general
path+=(~/.local/bin)
fpath+=(~/.zsh)
set -o emacs
function title() {
    print -Pn -- "\e]2;%(!.@@@ .)%c\a"
}
autoload -Uz add-zsh-hook
add-zsh-hook -Uz precmd title

# history settings
HISTFILE=~/.cache/zsh_history
HISTSIZE=50000
SAVEHIST=10000
setopt appendhistory
setopt sharehistory
setopt histfcntllock
setopt histignorealldups

# source it up
source ~/.zsh/aliases.zsh
source ~/.zsh/plugin-loader.zsh
source ~/.zsh/keybinds.zsh
#source ~/.zsh/prompt.zsh
source ~/.zsh/fzf.zsh
source ~/.zsh/fzf-tab.zsh
source ~/.zsh/lsd.zsh
source ~/.zsh/completion-list-colors.zsh
source ~/.zsh/manydots-magic.zsh
[[ ! -f ~/.zsh/local.zsh ]] || source ~/.zsh/local.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.zsh/p10k.zsh ]] || source ~/.zsh/p10k.zsh
