# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# general
PATH=$PATH:~/.local/bin
fpath+=(~/.zsh)
title() { export TITLE="$*" }
precmd() { print -Pn "\e]2;%(!.@@@ .)%~\a" }
set -o emacs

# history settings
HISTFILE=~/.cache/zsh_history
HISTSIZE=50000
SAVEHIST=10000
setopt appendhistory
setopt sharehistory
setopt histfcntllock
setopt histignorealldups

# exports
if [[ -x "$(command -v nvim)" ]]; then
    export EDITOR='nvim'
else
    export EDITOR='vim'
fi
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export ZSH_AUTOSUGGEST_USE_ASYNC=1

# source it up
source ~/.zsh/plugin-loader.zsh
source ~/.zsh/keybinds.zsh
source ~/.zsh/aliases.zsh
#source ~/.zsh/prompt.zsh
source ~/.zsh/fzf.zsh
source ~/.zsh/lsd.zsh
source ~/.zsh/completion-list-colors.zsh
source ~/.zsh/manydots-magic.zsh
source ~/.zsh/lfcd.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.zsh/p10k.zsh ]] || source ~/.zsh/p10k.zsh
